# Database Credentials
DATABASE_IP = "localhost" #IP of the mysql database
DATABASE_NAME = "nameHere" #Name of the database
DATABASE_USER = "unameHere" #Name of the database user
DATABASE_PASS = "passHere" #Database password

# Account IDs that are exempt from the contraband check
exemptAccountIds = [] #Add account ids here (comma separated)

# Items to search for
contrabandIds = [
    {"id": 14128, "name": "Atlantis Squid Helm"},
    {"id": 6655, "name": "Stig's Helmet"},
    {"id": 9947, "name": "Sentinel Grunt Helm"},
    {"id": 9948, "name": "Venture Grunt Helm"},
    {"id": 9949, "name": "Assembly Grunt Helm"},
    {"id": 7791, "name": "Blue Headdress"},
    {"id": 12305, "name": "Nuckal's Head"},
    {"id": 13779, "name": "Nexus Naomi's Helmet"},
    {"id": 13101, "name": "Sensei Wu's Hat and Beard"},
    {"id": 10155, "name": "Duke Exeter's Hair"},
    {"id": 13302, "name": "Doc Overbuild's Helmet"},
    {"id": 12886, "name": "Cyborg Helmet"},
    {"id": 13912, "name": "Hat of Magecraft"},
    {"id": 13913, "name": "Hat of the Adept"},
    {"id": 13911, "name": "Hat of Wizardry"},
    {"id": 13917, "name": "Hood of the Sage"},
    {"id": 2988, "name": "Red Conical Hat"},
    {"id": 5674, "name": "NPC Hi Tech Armor"},
    {"id": 12100, "name": "Ice Backpack"},
    {"id": 3849, "name": "Skunkbuster Backpack"},
    # {"id": 10476, "name": "Stromling Backpack"},
    {"id": 11293, "name": "NPC Grunt Armor Red"},
    {"id": 13312, "name": "Doc Overbuild's Armor"},
    {"id": 10156, "name": "Duke Exeter's Armor"},
    {"id": 10053, "name": "Hael Storm's Armor"},
    {"id": 8600, "name": "Old Skool Shirt"},
    {"id": 8359, "name": "Referee Shirt"},
    {"id": 8605, "name": "Soccer Uniform"},
    {"id": 10130, "name": "Weightlifter Shirt"},
    {"id": 12792, "name": "Harlequin Costume Legs"},
    {"id": 12793, "name": "Lederhosen Legs"},
    {"id": 12667, "name": "Handy Spanner"},
    {"id": 14571, "name": "Red Scorpion's Stinger"},
    {"id": 7641, "name": "Coalessa's Staff"},
    {"id": 10430, "name": "Stromling Dagger"},
    {"id": 14191, "name": "Hatchling Frog's Egg - Green"},
    {"id": 14560, "name": "Hatchling Frog's Egg - Red"},
    {"id": 14561, "name": "Hatchling Frog's Egg - Yellow"},
    {"id": 14559, "name": "Hatchling Frog's Egg - Dark Gray"},
    {"id": 14194, "name": "Hatchling Dog's Bone - Brown"},
    {"id": 14569, "name": "Hatchling Dog's Bone - Red"},
    {"id": 14568, "name": "Hatchling Dog's Bone - Dark Gray"},
    {"id": 14570, "name": "Hatchling Dog's Bone - Reddish Brown"},
    {"id": 14192, "name": "Hatchling Cat's Fish - White"},
    {"id": 14562, "name": "Hatchling Cat's Fish - Black"},
    {"id": 14563, "name": "Hatchling Cat's Fish - Tan"},
    {"id": 14564, "name": "Hatchling Cat's Fish - Orange"},
    {"id": 14193, "name": "Hatchling Mouse's Cheese - Light Gray"},
    {"id": 14802, "name": "Wan Wan Wolf Head"},
    {"id": 8535, "name": "Explorer Air Tank"},
    {"id": 12099, "name": "Tesla Backpack"},
    {"id": 15918, "name": "Athlete's Shade"},
    {"id": 15989, "name": "Purple Hood with Maelstrom Axe"},
    {"id": 16123, "name": "Murasaki Hakama"},
    {"id": 14803, "name": "Nya's Golden Dagger"},
    {"id": 13923, "name": "Elite Force Blade"},
    {"id": 13919, "name": "Elite Halberd"},
    {"id": 13921, "name": "Superior Crossbow of Blasting"},
    {"id": 14107, "name": "Exceptional Pea Shooter MK la"},
    {"id": 13918, "name": "Heroic Halberd"},
    {"id": 13922, "name": "Heroic Force Blade"},
    {"id": 12774, "name": "Super Frankfurter"},
    {"id": 14109, "name": "The Furious Morning Star"},
    {"id": 14108, "name": "The Terrible Wand"},
    {"id": 10154, "name": "Duke Exeter's Sword"},
    {"id": 10054, "name": "Hael Storm's Cutlass"},
    {"id": 13309, "name": "Vanda Darkflame's Katana"},
    {"id": 8519, "name": "Johnny Thunder's Whip"},
    {"id": 8080, "name": "Epsilon Starcracker's Blaster"},
    {"id": 12450, "name": "Skeleton Engineer's Blaster"},
    {"id": 1727, "name": "Flying Jetpack"},
    {"id": 13276, "name": "Adventure Valiant"},
    {"id": 13278, "name": "Inventor Valiant"},
    {"id": 13275, "name": "Shinobi Valiant"},
    {"id": 13277, "name": "Space Ranger Valiant"},
    {"id": 14099, "name": "Racemaster Helmet"},
    {"id": 14095, "name": "Racemaster Shirt"},
    {"id": 14098, "name": "Race Ace Helmet"},
    {"id": 14096, "name": "Race Ace Shirit"},
    {"id": 14097, "name": "Master Driver Helmet"},
    {"id": 14100, "name": "Master Driver Shirt"},
    {"id": 14116, "name": "4 Riders Shirt"},
    {"id": 14117, "name": "Kinga Hurl Shirt"},
    {"id": 14118, "name": "Murgle Blotch Shirt"},
]

# Inventory types to search
inventoryTypes = [
    {"id": 0, "name": "Items",              "search": True},
    {"id": 1, "name": "Vault_Items",        "search": True},
    {"id": 2, "name": "Bricks",             "search": False},
    {"id": 3, "name": "Models_in_BBB",      "search": False},
    {"id": 4, "name": "Temp_Items",         "search": True},
    {"id": 5, "name": "Models",             "search": False},
    {"id": 6, "name": "Temp_Models",        "search": False},
    {"id": 7, "name": "Behaviors",          "search": False},
    {"id": 8, "name": "Property_Deeds",     "search": False},
    {"id": 9, "name": "Bricks_In_BBB",      "search": False},
    {"id": 10, "name": "Vendor",            "search": False},
    {"id": 11, "name": "Vendor_Buyback",    "search": False},
    {"id": 12, "name": "Quest",             "search": True},
    {"id": 13, "name": "Donation",          "search": False},
    {"id": 14, "name": "Vault_Models",      "search": False},
    {"id": 15, "name": "Item_Sets",         "search": False}
]